mysql:
  ip: "192.168.1.102"   #ip地址
  user: "root"      #数据库用户的名字
  pwd: "123456"  #数据库用户的密码
  db_name: "user" #所连接数据库的名字
  db_port: "3306" #连接数据库的端口号
redis:
  ip: "192.168.1.102"   #ip地址
  db_name: 0 #所连接数据库的名字
  db_port: "6379" 
server:
  http_port: "8000" #HttpServer port
